AWSTemplateFormatVersion: '2010-09-09'
Resources:
  euwest1ecsinstanceprofile:
    Properties:
      Path: /
      Roles:
        - !Ref 'euwest1ecsrole'
    Type: AWS::IAM::InstanceProfile
  euwest1ecslive:
    Properties:
      ClusterName: live
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
    Type: AWS::ECS::Cluster
  euwest1ecsliveautoscalinggroup:
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref 'euwest1ecslivelaunchtemplate'
        Version: !GetAtt 'euwest1ecslivelaunchtemplate.LatestVersionNumber'
      MaxSize: 1
      MinSize: 1
      VPCZoneIdentifier:
        - subnet-0777c674d3018efd6
        - subnet-0dec29b6660100d8d
        - subnet-095d86cbe447af65e
    Type: AWS::AutoScaling::AutoScalingGroup
  euwest1ecslivelaunchtemplate:
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 30
        CreditSpecification:
          CpuCredits: Unlimited
        IamInstanceProfile:
          Arn: !GetAtt 'euwest1ecsinstanceprofile.Arn'
        ImageId: ami-09cec0d91e6d220ea
        InstanceType: t3.micro
        KeyName: live-eu-west-1
        SecurityGroupIds:
          - !GetAtt 'euwest1ecslivesg.GroupId'
      LaunchTemplateName: ecs-live-launch-template
    Type: AWS::EC2::LaunchTemplate
  euwest1ecslivesg:
    Properties:
      GroupDescription: Security Group for ECS Live Cluster
      VpcId: vpc-0e2786487ff4f2ef4
    Type: AWS::EC2::SecurityGroup
  euwest1ecslivesgingresscluster:
    Properties:
      GroupId: !GetAtt 'euwest1ecslivesg.GroupId'
      IpProtocol: '-1'
      SourceSecurityGroupId: !GetAtt 'euwest1ecslivesg.GroupId'
    Type: AWS::EC2::SecurityGroupIngress
  euwest1ecslivesgingressmanagement:
    Properties:
      CidrIp: 86.162.11.226/32
      GroupId: !GetAtt 'euwest1ecslivesg.GroupId'
      IpProtocol: '-1'
    Type: AWS::EC2::SecurityGroupIngress
  euwest1ecsrole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ecs:CreateCluster
                  - ecs:DeregisterContainerInstance
                  - ecs:DiscoverPollEndpoint
                  - ecs:Poll
                  - ecs:RegisterContainerInstance
                  - ecs:StartTelemetrySession
                  - ecs:Submit*
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetAuthorizationToken
                Effect: Allow
                Resource: '*'
          PolicyName: ecs-service
    Type: AWS::IAM::Role

