Description: eu-west-1 VPC
Resources:
  euwest1internetgateway:
    Type: AWS::EC2::InternetGateway
  euwest1publicroute:
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'euwest1internetgateway'
      RouteTableId: !Ref 'euwest1publicroutetable'
    Type: AWS::EC2::Route
  euwest1publicroutetable:
    Properties:
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::RouteTable
  euwest1vpc:
    Properties:
      CidrBlock: 10.128.0.0/20
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
    Type: AWS::EC2::VPC
  euwest1vpcgatewayattachment:
    Properties:
      InternetGatewayId: !Ref 'euwest1internetgateway'
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::VPCGatewayAttachment
  privateeuwest1a:
    Properties:
      AvailabilityZone: eu-west-1a
      CidrBlock: 10.128.3.0/24
      MapPublicIpOnLaunch: 'false'
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::Subnet
  privateeuwest1b:
    Properties:
      AvailabilityZone: eu-west-1b
      CidrBlock: 10.128.4.0/24
      MapPublicIpOnLaunch: 'false'
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::Subnet
  privateeuwest1c:
    Properties:
      AvailabilityZone: eu-west-1c
      CidrBlock: 10.128.5.0/24
      MapPublicIpOnLaunch: 'false'
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::Subnet
  publiceuwest1a:
    Properties:
      AvailabilityZone: eu-west-1a
      CidrBlock: 10.128.0.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::Subnet
  publiceuwest1asubnetroutetableassociation:
    Properties:
      RouteTableId: !Ref 'euwest1publicroutetable'
      SubnetId: !Ref 'publiceuwest1a'
    Type: AWS::EC2::SubnetRouteTableAssociation
  publiceuwest1b:
    Properties:
      AvailabilityZone: eu-west-1b
      CidrBlock: 10.128.1.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::Subnet
  publiceuwest1bsubnetroutetableassociation:
    Properties:
      RouteTableId: !Ref 'euwest1publicroutetable'
      SubnetId: !Ref 'publiceuwest1b'
    Type: AWS::EC2::SubnetRouteTableAssociation
  publiceuwest1c:
    Properties:
      AvailabilityZone: eu-west-1c
      CidrBlock: 10.128.2.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref 'euwest1vpc'
    Type: AWS::EC2::Subnet
  publiceuwest1csubnetroutetableassociation:
    Properties:
      RouteTableId: !Ref 'euwest1publicroutetable'
      SubnetId: !Ref 'publiceuwest1c'
    Type: AWS::EC2::SubnetRouteTableAssociation

