Description: eu-west-1 s3
Resources:
  euwest1managementbucket:
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: mgmt.eu-west-1.weblox.io
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Id: ExpireLogs
            Prefix: logs/
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'true'
        BlockPublicPolicy: 'true'
        IgnorePublicAcls: 'true'
        RestrictPublicBuckets: 'true'
    Type: AWS::S3::Bucket

